### ISSUE TITLE
Unlatch not possible if not locked

### ISSUE THREAD

**Issue by Phalynx** [mabunixda/node-red-contrib-nuki#10]
The lockSction "UNLATCH" is not possible if Nuki is not locked, but I need to unlatch even / open the door even when not locked. I have no autolock enabled, as my door has no opening knob on the outdoor side. Tried with v0.4.0

**Comment by mabunixda** [comment]
yes that's right .. at the moment the state is checked to be locked.
so the state of your nuki is unlocked at the moment you trigger unlatch ?

**Comment by Phalynx** [comment]
Exactly. It's not locked, and I use unlatch to open the door.
