### ISSUE TITLE
Nuki Bridge lost config

### ISSUE THREAD

**Issue by toulouzz** [mabunixda/node-red-contrib-nuki#16]
Hi,

I got a problem everyu two or three day my nuki-bridge config node seems to lose the configuration.
I got to open it, and click on the Update button to make it work again.

In fact, when i reboot my Raspberry, i have to update the config too.
Every information still stored in the node but i have to click on the update button for nodered to register them

Can you help me please ?

Thanks

Thomas

**Comment by mabunixda** [comment]
Oh that's wired ... 
Node-red is a default installation on the raspi?

**Comment by toulouzz** [comment]
Yes
I found the solution with a command node which renew the auth process
