### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Tomschin** [mabunixda/node-red-contrib-nuki#17]
The documentation shows 3 nodes. In my installation are only 2 nodes available. 

"nuki bridge in" connects properly to my bridge. 
"control in" let me select my lock but is not able to communicate with it.

Maybe just a beginners problem. Please could you help me? Contact information is available in my profile.

**Comment by Armageddit** [comment]
i think the 3. node is the group itself?
i got "nuki bridge in" and "control in"

i dont get infos if i unlock or lock :(
but i can ask for 

topic = lockStatus
payload = UNLOCKED

topic = lockStatus
payload = LOCKED

or send actions

topic = lockAction
payload = UNLOCK

**Comment by mabunixda** [comment]
yes you are right - the 3rd node is a configuration node.

@Tomschin need any further help?

**Comment by Tomschin** [comment]
Yes. Sorry for not responding.

Thanks Armageddit for your help. Now I can control the lock and ask for its state.

But receiving a trigger for a lock action is what I am looking for. I want to switch some stuff when I arrive in my apartment. Is frequent polling really the only way?

I have a MQTT Broker. Maybe someone knows a way to connect the lock/bridge with the broker and get my trigger from this source.

**Comment by Tomschin** [comment]
Found this via Google https://github.com/bluewalk/NukiBridge2Mqtt
I will try it and post my results here.

**Comment by Armageddit** [comment]
oh yes, I also miss that it triggers and sends me messages.
if that works with MQTT that would be ok too, since I have a server running for zigbee anyway.

**Comment by mabunixda** [comment]
@Armageddit @Tomschin i splitted this into the ticket #19

**Comment by Tomschin** [comment]
I tried to install the docker image. But it failed.
As you can read there https://github.com/bluewalk/NukiBridge2Mqtt/issues/28 I am not the first one.
So as I am a beginner, I would like to ask if someone is willing to create a 32bit version. 
If not, please stay tuned until I learned how to do it. ;)
