### ISSUE TITLE
trigger on updates

### ISSUE THREAD

**Issue by mabunixda** [mabunixda/node-red-contrib-nuki#19]
oh yes, I also miss that it triggers and sends me messages.
if that works with MQTT that would be ok too, since I have a server running for zigbee anyway.

_Originally posted by @Armageddit in https://github.com/mabunixda/node-red-contrib-nuki/issues/17#issuecomment-790813881_

**Comment by Tomschin** [comment]
I tried to install the docker image. But it failed.
As you can read there bluewalk/NukiBridge2Mqtt#28 I am not the first one.
So as I am a beginner, I would like to ask if someone is willing to create a 32bit version.
If not, please stay tuned until I learned how to do it. ;)

**Comment by mabunixda** [comment]
Which docker image are you using?

**Comment by Tomschin** [comment]
I used this comand inside docker:

pi@Pi:~ $ docker run -d --name nukibridge2mqtt bluewalk/nukibridge2mqtt -e BRIDGE_TOKEN=[snip] -e MQTT_HOST=pi
Unable to find image 'bluewalk/nukibridge2mqtt:latest' locally
latest: Pulling from bluewalk/nukibridge2mqtt
801bfaa63ef2: Pull complete
5baca56f7803: Pull complete
d469d9f5e0c9: Pull complete
1957dd049170: Pull complete
b1a4d113b47b: Pull complete
Digest: sha256:bc29b7f753588eadd6052ea448972af3511fa5d3641b25dfdcc9effe3ae81816
Status: Downloaded newer image for bluewalk/nukibridge2mqtt:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was
requested
160886c381391c38b8ca21de98b9fbc5f122b5348e06d816b1eaebe007ac80c7

**Comment by mabunixda** [comment]
thats a nukibridge2mqtt problem and not related to this module? bluewalk must create a multi-arch docker image
