### ISSUE TITLE
"ReferenceError: node is not defined" on Nuki bridge in

### ISSUE THREAD

**Issue by eddriesen** [mabunixda/node-red-contrib-nuki#34]
topic = info , payload is empty string. Node red is V2.1.3 (on home assistant 2021.11.4 , hassio on nuc)
![2021-11-18 17_26_00-Window](https://user-images.githubusercontent.com/29610617/142458719-f0edb8b4-9107-4b3b-abff-3bf39cc24643.png)
Am I missing gomething? PEBCAK?

The lock state is working, so I guess the api key was entered correctly (I removed non alphanumericals frop api token to be sure)

Any input appreciated!

`
[
    {
        "id": "3e7b58e1dcc30f91",
        "type": "inject",
        "z": "b8639e6a.01d96",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "info",
        "payloadType": "str",
        "x": 200,
        "y": 760,
        "wires": [
            [
                "0c833d02b737b2c4"
            ]
        ]
    },
    {
        "id": "0c833d02b737b2c4",
        "type": "nuki-bridge-control",
        "z": "b8639e6a.01d96",
        "name": "192.168.4.180:8080",
        "bridge": "5c55fc6808ab8e66",
        "x": 480,
        "y": 700,
        "wires": [
            [
                "1718e1e325923e2e"
            ]
        ]
    },
    {
        "id": "1718e1e325923e2e",
        "type": "debug",
        "z": "b8639e6a.01d96",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 930,
        "y": 700,
        "wires": []
    },
    {
        "id": "5c55fc6808ab8e66",
        "type": "nuki-bridge",
        "host": "192.168.4.180",
        "port": "8080"
    }
]
`

**Comment by Chrischi-** [comment]
Not PEBCAK :wink:

see PR https://github.com/mabunixda/node-red-contrib-nuki/pull/33

this needs to be fixed by @mabunixda

**Comment by eddriesen** [comment]
> Not PEBCAK 😉
> 
> see PR #33
> 
> this needs to be fixed by @mabunixda

danke shön! Can do raw api calls for the moment if needed. Did read the api ref document. Api doesn't provide lock/unlock log atm, so no hurry. Wanted to visualize access log in Home assistant, but that won't work for now via the gw api. Maybe via nuki web.
