### ISSUE TITLE
Unlock/Lock Log

### ISSUE THREAD

**Issue by mabunixda** [mabunixda/node-red-contrib-nuki#36]
> Not PEBCAK 😉
> 
> see PR #33
> 
> this needs to be fixed by @mabunixda

danke shön! Can do raw api calls for the moment if needed. Did read the api ref document. Api doesn't provide lock/unlock log atm, so no hurry. Wanted to visualize access log in Home assistant, but that won't work for now via the gw api. Maybe via nuki web.

_Originally posted by @eddriesen in https://github.com/mabunixda/node-red-contrib-nuki/issues/34#issuecomment-975253812_

**Comment by mabunixda** [comment]
probably the web api does report this already.

If you are able to add the callback functionality to the node which is referenced in the (node-bridge-api)[https://github.com/Mik13/nuki-bridge-api#callbacks] then you would receive active updates about the current state of the lock - *if* this state gets asap updated to the bridge as well. But if the Web API is able to get these updates, they must be published by the bridge -> so there is a big change that those updates are available.

I missed/failed to implement these callback ...

**Comment by mabunixda** [comment]
@eddriesen you will be able get this information by the web API integration happening in #38 ... will take some time testing this and hopefully also integrate some bridge behavior into

**Comment by mabunixda** [comment]
with the latest commit in the alpha branch also the actual callbacks are working 👍

**Comment by mabunixda** [comment]
Please try with version 1.1.0

**Comment by eddriesen** [comment]
Hey, just to let you know, I'm on it and will report back. Just struggling with "AttachHandlers: Could not get nuki". I'm presuming that I need to sort out my "bridge callback host".
