### ISSUE TITLE
Web api integration

### ISSUE THREAD

**Issue by mabunixda** [mabunixda/node-red-contrib-nuki#37]
>  Does it make sense to implement also the web API in this node?

This would be helpful to simplify such a node setup:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/37173958/144817456-fef29015-13ac-4682-87fb-166a20967a87.png">

I use exactly this setup to get the push notification from the Nuki.io API in case the door gets opened/closed. But I wonder if the door state is also available early on the bridge, rather than the Nuki.io API

_Originally posted by @djiwondee in https://github.com/mabunixda/node-red-contrib-nuki/issues/13#issuecomment-986606425_

**Comment by djiwondee** [comment]
Why not? 👍🏻 

Information from the web API ate much more comprehensive.

```
smartlockId: {{MySmartlockId:}}
accountId: {{MyAccountId}}
type: 0
authId: {{myAuthId}}
name: "Haustür"
favorite: false
config: object
> name: "Haustür"
> latitude: {{SomeValue}}
> longitude: {{SomeValue}}
> autoUnlatch: true
> liftUpHandle: false
> pairingEnabled: true
> buttonEnabled: true
> ledEnabled: false
> ledBrightness: 1
> timezoneOffset: 0
> daylightSavingMode: 0
> fobPaired: false
> fobAction1: 4
> fobAction2: 1
> fobAction3: 2
> singleLock: true
> advertisingMode: 0
> keypadPaired: false
> homekitState: 3
> timezoneId: 37
advancedConfig: object
> totalDegrees: 685
> singleLockedPositionOffsetDegrees: -90
> unlockedToLockedTransitionOffsetDegrees: 0
> unlockedPositionOffsetDegrees: 90
> lockedPositionOffsetDegrees: -90
> detachedCylinder: false
> batteryType: 1
> autoLock: false
> autoLockTimeout: 300
> autoUpdateEnabled: false
> lngTimeout: 20
> singleButtonPressAction: 1
> doubleButtonPressAction: 5
> automaticBatteryTypeDetection: true
> unlatchDuration: 3
state: object
> mode: 2
> state: 3
> trigger: 0
> lastAction: 3
> batteryCritical: false
> batteryCharging: false
> batteryCharge: 68
> keypadBatteryCritical: false
> doorsensorBatteryCritical: false
> doorState: 2
> ringToOpenTimer: 0
> nightMode: false
firmwareVersion: 133897
hardwareVersion: 2817
serverState: 0
adminPinState: 0
virtualDevice: false
creationDate: "2021-09-28T07:50:31.399Z"
updateDate: "2021-12-06T11:23:10.385Z"
```

That's why I'm asking whether _all_ information about the local lock is available on the bridge in advance of the web API.

Have in mind it requires an account on NUKI.io and the creation of a token for the connected lock.

**Comment by mabunixda** [comment]
yeah and a valid/stable internet connection ;-)

**Comment by mabunixda** [comment]
@djiwondee can you try the version from PR #38 by manually installing this version?

**Comment by djiwondee** [comment]
@mabunixda so manually installing would mean to grab the (six?) changed files from the `integrate-web-api` branch, since you don't have a development release of this for `npm install`

**Comment by djiwondee** [comment]
> A 1.1.0-alpha.1 version is now online

I've test it now on a fresh installed Raspi  _2_,  a clean node-red setup and will provide feedback here. 

Node-RED version: v2.1.4
Node.js  version: v14.18.2
Linux 5.10.63-v7+ arm LE

`npm` install warnings (in case you are interested in)

```raspi-smarthome-dev:~/.node-red $ npm i node-red-contrib-nuki@1.1.0-alpha.1
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
+ node-red-contrib-nuki@1.1.0-alpha.1
added 132 packages from 144 contributors and audited 214 packages in 48.286s
```
**My Test flow**
(Same as on my PROD environment)

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/37173958/144999749-3a3db5aa-d043-4208-ad5d-cd4673e4cbfa.png">

**Test Experience** 

Each tested command (excl. `reboot` and  `fwupdate` on nuki bridge in) has been executed successful resulting in lock/bridge activities as expected.

1) For just one lockAction:UNLOCK I got an error, which hasn't happened again for each further attempt
<img width="314" alt="image" src="https://user-images.githubusercontent.com/37173958/145000409-245bbfec-0b91-4455-a417-719256fa4dcb.png">

2) I wonder why nuki key:value payload is always _undefined_ in the response (please see the img above in 1)

3) To me it is not clear what the payload _true_ || _false_ indicates for a `lock:Action`. 

<img width="237" alt="image" src="https://user-images.githubusercontent.com/37173958/145002033-6e47402d-ec7e-41f2-b3ef-1d7ccf0ee9f9.png">

Does it mean successful API request and it is needed to execute `lockStatus` to get the details about the `lock:Action`result. Or does this mean what ever `lockAction:*` has been executed, it was un-/successful and the intended status of the lock can be assumed/guarantied?

4) I would love to get a _web state_ key:value payload after _each_ `lockAction:*` as a confirmation of the _real_ lock state

5) Much better would be to get a _bridge based_ lock state key/value payload after each `lockAction:*` as confirmation after each action based change.

The [known issue of "Can`t select a NUKI in Dropdown"](https://github.com/mabunixda/node-red-contrib-nuki/issues/13#issuecomment-662896966) didn't appear as well.

Overall it looks stable so far! Great work, thank you very much!

**Comment by mabunixda** [comment]
@djiwondee thanks for testing, did you also try the ```lockStatus``` action, after adding your Web API Key to the bridge configuration?

ad 1) yeah I have also seen this error appear, but I do not know what the root cause is/was

ad 2) the nuki reference is the nuki object itself that will be removed. I gonna replace it by the nukiId - so the id of your actual nuki

ad 3) the payload true/false is the response of the underlying library to the actual request/action. this is just used in this payload. At the moment before doing a lockAction the status of the nuki gets requested to not interact if the status is unknown or the lock is uncalibrated. The status of the lock can be assumed to be in the requested state, if the payload is true.

ad 4) try lockStatus - when you add your web API key within the bridge configuration, the web status gets queried. But the web status is not always in sync with the actual lock status - that may take some time to be synced. That's my experience from the Web UI of Nuki.

ad 5) can be integrated changed in the behavior, like already written in 3

**Comment by djiwondee** [comment]
> did you also try the lockStatus action, after adding your Web API Key to the bridge configuration?

I've recognized this new parameter in the node config and have of course entered my own value into it :-) Guess that's the "enabler" to see the so called _web state_ payload on `lockAction:STATUS`.

**Comment by mabunixda** [comment]
yes it is the enable - at the moment in this initial code also the only interaction with the web API. May be more to come on request 👍

**Comment by djiwondee** [comment]
> At the moment before doing a lockAction the status of the nuki gets requested to not interact if the status is unknown or the lock is uncalibrated

Where is this information coming from? WebAPI _or_ bridge/lock local connection infor

**Comment by mabunixda** [comment]
> > At the moment before doing a lockAction the status of the nuki gets requested to not interact if the status is unknown or the lock is uncalibrated
> 
> Where is this information coming from? WebAPI _or_ bridge/lock local connection infor

This is just local information from the bridge/lock. For interaction only local bridge connectivity is used

**Comment by djiwondee** [comment]
> this is just local information from the bridge/lock. For interaction only local bridge connectivity is used

That's exactly what I think its needed, most recent lock status captured from the bridge locally. This would prevent the latency requesting info from the web API.

Happy to support further testing, if applicable!

**Comment by mabunixda** [comment]
Well the question is, should the node automatically fetch the status from the bridge/lock or is it valid as it is to just use true/false and decide in a node-red logic to fetch the status again afterwards...

**Comment by djiwondee** [comment]
The key is in my point of view, to have a push info about state changes at all. This is exactly what [this flow](https://github.com/mabunixda/node-red-contrib-nuki/issues/13#issuecomment-986606425) does. The web API does a proactive callback, which allows to use lock state or door sensor state changes to trigger something else (e. g. alarm for home security in case of unattended entry through the door or at lease lock opening).

**Comment by mabunixda** [comment]
with the latest commit in the alpha branch also the actual callbacks are working 👍  and fixxes also #36

**Comment by mabunixda** [comment]
Please try it with version 1.1.0

**Comment by djiwondee** [comment]
> Please try it with version 1.1.0

Did it! Seems to work from a setup perspective.

but there appears one error in the node-red-log with each data fetch:
```
11 Jan 12:06:42 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
11 Jan 12:07:12 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
11 Jan 12:07:42 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
11 Jan 12:08:12 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
11 Jan 12:08:42 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
11 Jan 12:09:12 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
11 Jan 12:09:42 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
11 Jan 12:10:12 - [info] [nuki-lock-control:0c7ace53fec71b7a] -error: could not get web lock state: {}
```
I wonder about it since Nuki Web knows the status:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/37173958/148934419-b0f257ad-37cb-44ca-9989-53028c2e3071.png">

**Comment by mabunixda** [comment]
@djiwondee yeah that's strange. and the error message `{}` does not tell more about what's going on :(

**Comment by djiwondee** [comment]
And btw.: there is a broken link _For more examples/values go to **documentation**_:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/37173958/148937983-5542de4b-c36d-4146-b306-d8584465609a.png">

**Comment by djiwondee** [comment]
@mabunixda can you please clarify some more what is required here:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/37173958/148941041-69444e7d-f9bc-4458-811e-ac31d46cfe53.png">

1. my own node-red host with a flow using your nuki bridge control node?
2. my own node-red host with a flow using my own nuki web call back request?
3. the Nuki-Web configured call back url for access via "https://api.nuki.io/smartlock/"?

Which sense makes the parameter `WEB API Token` and where is it used?
Do you have your own sample flow for eating this feature.

**Comment by mabunixda** [comment]
Yeah - that must be rewritten :( The meaning is your actual node-red host URL where requests can be handled - e.g. `http://192.168.1.1/node-red`. An idea would be to add a test function that validates this setting. Node-red does not know about its actual URL which your are accessing ... So this must be configured manually

**Comment by djiwondee** [comment]
> Yeah - that must be rewritten :( The meaning is your actual node-red host URL where requests can be handled - e.g. `http://192.168.1.1/node-red`. An idea would be to add a test function that validates this setting. Node-red does not know about its actual URL which your are accessing ... So this must be configured manually

Is it a GET- or a POST-HTTP request you are performing for web callback?

Which sense makes the parameter `WEB API Token` and where/how is it used in your web callback?

**Comment by mabunixda** [comment]
The Nuki Bridge is performing a web callback to the [node-red setup](https://github.com/mabunixda/node-red-contrib-nuki/blob/main/nuki/nuki.js#L22) - and in this case it is a POST-HTTP request that is done here. 

The WEB API Token is has nothing to do with the Web Callback - I must update the naming, but have not idea what are meaningful naming conventions. The WEB API token is the token, that is used to communicate with the WEB API of Nuki ( api.nuki.io ). 

So the Bridge Callback Host must be renamed .. to .. i do not know :(

**Comment by Nicao** [comment]
Sorry, I'm just confused... Running node red on home assistant I am seriously lost what to configure as Bridge Callback host. Do I need this setting if just using it locally?

**Comment by mabunixda** [comment]
You  just need this to get the callbacks from the bridge. Eg when the door gets locked manually
