### ISSUE TITLE
No coupling with Nuki

### ISSUE THREAD

**Issue by bergjet** [mabunixda/node-red-contrib-nuki#5]
I have a token and the IP address, it works in ioBroker. But not in the node-red node

**Comment by mabunixda** [comment]
What do you understand with coupling?
Are any Nukis listed after configuration of the bridge?

**Comment by bergjet** [comment]
Keine Verbindung zu Nuki
Es wird mir kein Nuki angezeigt. Im ioBroker funktioniert es.

**Comment by mabunixda** [comment]
im ioBroker heisst was genau?
Es sollte folgender output im node-red log output auftauchen:

> 26 Aug 11:27:55 - [info] [nuki-bridge:81f5214b.bd586] Got 1 nukis from bridge 192.168.1.10

**Comment by mabunixda** [comment]
no further input -> resolved?
